### ISSUE TITLE
关于Firebase和GDT冲突命名的问题你解决了吗？

### ISSUE THREAD

**Issue by metromancn** [zengqingf/iOSAppLanguageSwitch#2]
不好意思，没有找到你的联系方式，借这个地方发个消息。
看到你在FirebaseIOS上面提的问题了：关于Firebase和GDT冲突命名的问题，我看到Google已经在新版本修正了命名，但是没有发布到cocoapods上，另外我直接pod github 最新版也还是旧的。请问你解决这个问题了吗？能否请教解决办法？我邮箱：metromancn@gmail.com

**Comment by zengqingf** [comment]
@metromancn 在GDTEvent.h这个文件中，强制宏定义类名  #define GDTEvent XXGDTEvent

**Comment by metromancn** [comment]
谢谢，解决了。
